### ISSUE TITLE
Fail while npm install 

### ISSUE THREAD

**Issue by ashkan-pirmani** [OHDSI/ArachneUI#710]
Hi everyone!
I am newbie at node , and try to compile this code, and at first step, I have multiple warns and error!
node : 12.13.0
npm:6.12.0
 I have tried this on win10X64, macOS Catalina and Ubuntu
but I was failed!

Thank you
```
39155 warn arachne-ui@1.16.5 No license field.
39156 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
39157 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
39158 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
39158 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
39158 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
39158 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
39159 verbose stack Error: node-sass@4.9.0 postinstall: `node scripts/build.js`
39159 verbose stack Exit status 1
39159 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
39159 verbose stack     at EventEmitter.emit (events.js:210:5)
39159 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
39159 verbose stack     at ChildProcess.emit (events.js:210:5)
39159 verbose stack     at maybeClose (internal/child_process.js:1021:16)
39159 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
39160 verbose pkgid node-sass@4.9.0
39161 verbose cwd C:\Users\ashka\ArachneUI
39162 verbose Windows_NT 10.0.18363
39163 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
39164 verbose node v12.13.0
39165 verbose npm  v6.12.0
39166 error code ELIFECYCLE
39167 error errno 1
39168 error node-sass@4.9.0 postinstall: `node scripts/build.js`
39168 error Exit status 1
39169 error Failed at the node-sass@4.9.0 postinstall script.
39169 error This is probably not a problem with npm. There is likely additional logging output above.
39170 verbose exit [ 1, true ]
```

**Comment by YaroslavTir** [comment]
@ashkan-pirmani I know that a lot of time has passed since you ask the question :) . Were you able to overcome the issue?
