### ISSUE TITLE
Node cannot find public/js/server.js

### ISSUE THREAD

**Issue by blootsvoets** [OHDSI/ArachneUI#790]
When running the code with
```
npm install
npm run build
cd bin
npm install
PORT=8080 node index.js
```
I get the error (red: absolute file names redacted to `<path>`):
```
Error: Cannot find module '../public/js/server'
Require stack:
- <path>/ArachneUI/bin/server.js
- <path>/ArachneUI/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at <path>/ArachneUI/bin/server.js:71:34
    at Layer.handle [as handle_request] (<path>/ArachneUI/bin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (<path>/ArachneUI/bin/node_modules/express/lib/router/index.js:317:13)
    at <path>/ArachneUI/bin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (<path>/ArachneUI/bin/node_modules/express/lib/router/index.js:335:12)
    at next (<path>/ArachneUI/bin/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (<path>/ArachneUI/bin/node_modules/cookie-parser/index.js:57:14)
    at Layer.handle [as handle_request] (<path>/ArachneUI/bin/node_modules/express/lib/router/layer.js:95:5)
```

Am I missing an installation step? Or can I ignore this warning?

**Comment by blootsvoets** [comment]
This issue is not solved for me. I am now able to run it with nginx, but not with node.

**Comment by acumarav** [comment]
Hello @blootsvoets, this frontend application supposed to be used with the java API backend, please see: [ArachneCentralAPI](https://github.com/OHDSI/ArachneCentralAPI)
Can it work for you?

**Comment by blootsvoets** [comment]
Hi @acumarav, yes I'm also starting the central/node API. Those start up fine. However, the node server searches for a file that does not exist. Or is this just a warning that can be ignored?

**Comment by acumarav** [comment]
> Hi @acumarav, yes I'm also starting the central/node API. Those start up fine. However, the node server searches for a file that does not exist. Or is this just a warning that can be ignored?

Well, as you see - ArachneUI uses the node to run webpack and produce bundle, but after that, it gets packed by maven into resources zip file which is embedded by the backend API jar. So yes - if you can work with the nginx please do so and igrore this warning.
